### ISSUE TITLE
底板里的reset引脚已经使用了rc延时100ms，还需要单独接一个reset吗

### ISSUE THREAD

**Issue by warren-wzw** [CNflysky/RPI_DSI_Drivers#2]
大佬你好 底板里的reset引脚已经使用了rc延时100ms，还需要单独接一个reset吗

**Comment by CNflysky** [comment]
needn't. but i suggests use a pin to control the rst signal since some panel may requires proper power-on and reset sequence.
不需要。不过我建议是用一个引脚来控制rst信号，有些屏可能对上电时序和复位时序有要求。
